# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring.thymeleaf.cache=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG

spring.datasource.url=jdbc:oracle:thin:@2.47.57.110:1521:orcl
spring.datasource.username=USER16
spring.datasource.password=AKT16
spring.jpa.hibernate.ddl-auto=create
<<<<<<< HEAD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.show-sql=true
=======
spring.jpa.show-sql=true
>>>>>>> develop_luca
