# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/gynogym
spring.datasource.username=root
spring.datasource.password=$icureZZa00!!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true